name: Deploy to Vercel AI Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.repository, 'web') || contains(github.repository, 'neothink.com')
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '24.8.0'
          cache: 'npm'
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: AI Safety Pre-deployment Check
        run: |
          if [ -f "safety.config.json" ]; then
            npm install -g ai-safety-validator
            ai-safety-check --config=safety.config.json --deployment
          fi
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Post-deployment Health Check
        run: |
          sleep 30
          curl -f ${{ secrets.VERCEL_URL }}/api/health || exit 1